# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Information(object):
    def setupUi(self, Information):
        Information.setObjectName("Information")
        Information.resize(400, 257)
        Information.setAcceptDrops(False)
        self.label = QtWidgets.QLabel(Information)
        self.label.setGeometry(QtCore.QRect(20, 0, 371, 211))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Information)
        self.pushButton.setGeometry(QtCore.QRect(170, 220, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Information)
        QtCore.QMetaObject.connectSlotsByName(Information)

    def retranslateUi(self, Information):
        _translate = QtCore.QCoreApplication.translate
        Information.setWindowTitle(_translate("Information", "About"))
        self.label.setText(_translate("Information", "Программа позволяет сыграть мелодию на синтезаторе, при необходимости записать ее в базу данных (кнопки \"Начать запись\", \"Закончить запись\"), а так же воспроизводить мелодии (кнопка \"Воспроизвести запись\"), уже имеющиеся в базе данных.\n"
" При помощи кнопки \"Удалить запись\" выбранная мелодия удаляется из базы данных."))
        self.pushButton.setText(_translate("Information", "Закрыть"))
